version: '3.9'

services:
  friendlyfl-router:
    build:
      context: .
    image: friendlyfl-router
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    env_file:
      - .env
    command: bash -c "cron && poetry run python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - artifacts:/friendlyfl/artifacts

  postgres:
    image: postgres:12.9
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: UCalgary123

volumes:
  postgres_data: {}
  artifacts:  {}
