# Generated by Django 4.2.3 on 2023-07-15 15:44

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('friendlyfl', '0002_alter_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='logs',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=django_fsm.FSMField(choices=[('STANDBY', 'Standby'), ('PREPARING', 'Preparing'), ('RUNNING', 'Running'), ('PENDING_SUCCESS', 'Pending Success'), ('PENDING_FAILED', 'Pending Failed'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='STANDBY', max_length=50, protected=True),
        ),
    ]
