# Generated by Django 4.2.3 on 2023-07-22 19:16

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('friendlyfl', '0003_alter_run_logs_alter_run_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='middle_artifacts',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='run',
            name='tasks',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Standby'), (1, 'Preparing'), (2, 'Running'), (3, 'Pending Success'), (4, 'Pending Failed'), (5, 'Success'), (6, 'Failed')], default=0, protected=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='uid',
            field=models.UUIDField(unique=True),
        ),
    ]
