# Generated by Django 4.2.3 on 2023-08-19 20:19

from django.db import migrations, models
import django_fsm
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('friendlyfl', '0004_run_middle_artifacts_run_tasks_alter_project_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='site_uid',
            field=models.UUIDField(auto_created=uuid.UUID('2cdd9615-7ba7-4cf4-b28f-7db0d36d43c9'), default=uuid.UUID('56ca9956-3d1f-4669-991c-54758531498b')),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Failed'), (1, 'Pending Failed'), (2, 'Standby'), (3, 'Preparing'), (4, 'Running'), (5, 'Pending Success'), (6, 'Success')], default=2, protected=True),
        ),
    ]
