# Generated by Django 4.2.3 on 2023-08-26 19:58

from django.db import migrations, models
import django_fsm
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('friendlyfl', '0005_run_site_uid_alter_run_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='cur_seq',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='run',
            name='site_uid',
            field=models.UUIDField(default=uuid.UUID('ec262ca8-04f2-4173-8622-d61dce3bb7be')),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Failed'), (1, 'Pending Failed'), (2, 'Standby'), (3, 'Preparing'), (4, 'Running'), (5, 'Pending Success'), (6, 'Pending Aggregating'), (7, 'Aggregating'), (8, 'Success')], default=2, protected=True),
        ),
    ]
